In [1]:
import pandas as pd

In [2]:
df = pd.read_html("https://finance.yahoo.com/quote/F/history?p=F")[0]

In [3]:
df.head(3)

           Date   Open   High   Low Close* Adj Close**     Volume
0  Jan 15, 2021  10.04  10.05  9.82   9.83        9.83   99914900
1  Jan 14, 2021   9.81  10.20  9.79  10.17       10.17  112695300
2  Jan 13, 2021   9.91   9.92  9.64   9.78        9.78   89549300

In [4]:
df.describe()

                Date  Open  High   Low Close* Adj Close**    Volume
count            101   101   101   101    101         101       101
unique           101    81    81    82     83          83       101
top     Aug 31, 2020  9.31  9.32  8.78   8.82        8.82  53761800
freq               1     3     3     4      3           3         1

In [5]:
df = df.head(50).sort_values(by='Date')

In [6]:
df = df.drop([0, 32])

In [7]:
df = df.astype ({"Open":'float',
                 "High":'float',
                 "Low":'float',
                 "Close*":'float',
                 "Adj Close**":'float',
                 "Volume" :'float'})

In [8]:
df

            Date  Open   High   Low  Close*  Adj Close**       Volume
31  Dec 01, 2020  9.16   9.40  9.16    9.24         9.24   68970300.0
30  Dec 02, 2020  9.16   9.24  9.08    9.20         9.20   48345000.0
29  Dec 03, 2020  9.26   9.32  9.15    9.21         9.21   50302100.0
28  Dec 04, 2020  9.26   9.44  9.24    9.34         9.34   48775500.0
27  Dec 07, 2020  9.31   9.33  9.15    9.22         9.22   58305200.0
26  Dec 08, 2020  9.19   9.33  9.17    9.25         9.25   56296700.0
25  Dec 09, 2020  9.31   9.49  9.29    9.45         9.45   60780300.0
24  Dec 10, 2020  9.31   9.32  9.10    9.12         9.12   83372800.0
23  Dec 11, 2020  9.19   9.19  9.01    9.02         9.02   73438200.0
22  Dec 14, 2020  9.13   9.18  8.88    8.91         8.91   76826000.0
21  Dec 15, 2020  9.03   9.15  8.94    9.15         9.15   69665900.0
20  Dec 16, 2020  9.17   9.18  8.97    9.04         9.04   55274500.0
19  Dec 17, 2020  9.09   9.13  9.00    9.08         9.08   49301600.0
18  Dec 18, 2020  9.09   9.09  8.91    8.95         8.95   78764600.0
17  Dec 21, 2020  8.87   9.01  8.79    8.93         8.93   63908100.0
16  Dec 22, 2020  8.98   8.99  8.75    8.79         8.79   59031200.0
15  Dec 23, 2020  8.82   9.03  8.80    8.99         8.99   54086700.0
14  Dec 24, 2020  9.01   9.02  8.80    8.86         8.86   27927000.0
13  Dec 28, 2020  8.92   8.98  8.86    8.89         8.89   38068400.0
12  Dec 29, 2020  8.93   8.93  8.78    8.82         8.82   37537900.0
11  Dec 30, 2020  8.83   8.92  8.81    8.86         8.86   38461900.0
10  Dec 31, 2020  8.84   8.86  8.78    8.79         8.79   40135300.0
9   Jan 04, 2021  8.81   8.84  8.43    8.52         8.52   85043100.0
8   Jan 05, 2021  8.47   8.72  8.46    8.65         8.65   70127800.0
7   Jan 06, 2021  8.79   8.94  8.68    8.84         8.84   72590200.0
6   Jan 07, 2021  8.94   9.08  8.88    9.06         9.06   77117100.0
5   Jan 08, 2021  9.10   9.14  8.89    9.00         9.00   59121400.0
4   Jan 11, 2021  8.87   9.32  8.82    9.30         9.30   96129500.0
3   Jan 12, 2021  9.30   9.82  9.29    9.78         9.78  124808500.0
2   Jan 13, 2021  9.91   9.92  9.64    9.78         9.78   89549300.0
1   Jan 14, 2021  9.81  10.20  9.79   10.17        10.17  112695300.0
49  Nov 04, 2020  7.86   7.87  7.63    7.64         7.64   67326800.0
48  Nov 05, 2020  7.76   7.99  7.71    7.99         7.99   61442600.0
47  Nov 06, 2020  8.01   8.02  7.75    7.79         7.79   50912100.0
46  Nov 09, 2020  8.11   8.38  8.08    8.20         8.20  110511300.0
45  Nov 10, 2020  8.23   8.59  8.18    8.38         8.38   87468400.0
44  Nov 11, 2020  8.60   8.60  8.29    8.33         8.33   75644400.0
43  Nov 12, 2020  8.26   8.29  8.10    8.21         8.21   81064900.0
42  Nov 13, 2020  8.23   8.57  8.23    8.54         8.54   79475100.0
41  Nov 16, 2020  8.74   8.85  8.61    8.80         8.80   84853900.0
40  Nov 17, 2020  8.66   8.85  8.63    8.75         8.75   46754500.0
39  Nov 18, 2020  8.82   9.05  8.78    8.82         8.82   77759300.0
38  Nov 19, 2020  8.88   8.88  8.74    8.82         8.82   56672700.0
37  Nov 20, 2020  8.81   8.82  8.68    8.74         8.74   57024300.0
36  Nov 23, 2020  8.82   8.98  8.78    8.86         8.86   71537100.0
35  Nov 24, 2020  9.15   9.50  9.14    9.45         9.45   99520500.0
34  Nov 25, 2020  9.20   9.25  9.00    9.08         9.08   95217800.0
33  Nov 27, 2020  9.12   9.14  9.03    9.09         9.09   27853900.0

In [9]:
df.describe()

            Open       High        Low     Close*  Adj Close**        Volume
count  48.000000  48.000000  48.000000  48.000000    48.000000  4.800000e+01
mean    8.898333   9.023750   8.784583   8.910417     8.910417  6.782910e+07
std     0.439373   0.449788   0.447156   0.474687     0.474687  2.162257e+07
min     7.760000   7.870000   7.630000   7.640000     7.640000  2.785390e+07
25%     8.805000   8.850000   8.667500   8.780000     8.780000  5.329305e+07
50%     8.935000   9.040000   8.815000   8.920000     8.920000  6.814855e+07
75%     9.162500   9.267500   9.042500   9.162500     9.162500  7.987255e+07
max     9.910000  10.200000   9.790000  10.170000    10.170000  1.248085e+08

In [10]:
df.corr()

                 Open      High       Low    Close*  Adj Close**    Volume
Open         1.000000  0.954594  0.977427  0.926622     0.926622  0.051866
High         0.954594  1.000000  0.976968  0.987268     0.987268  0.222748
Low          0.977427  0.976968  1.000000  0.971545     0.971545  0.057488
Close*       0.926622  0.987268  0.971545  1.000000     1.000000  0.194933
Adj Close**  0.926622  0.987268  0.971545  1.000000     1.000000  0.194933
Volume       0.051866  0.222748  0.057488  0.194933     0.194933  1.000000

In [11]:
df['Gain'] = df['Close*']- df['Open']

In [12]:
df

            Date  Open   High   Low  Close*  Adj Close**       Volume  Gain
31  Dec 01, 2020  9.16   9.40  9.16    9.24         9.24   68970300.0  0.08
30  Dec 02, 2020  9.16   9.24  9.08    9.20         9.20   48345000.0  0.04
29  Dec 03, 2020  9.26   9.32  9.15    9.21         9.21   50302100.0 -0.05
28  Dec 04, 2020  9.26   9.44  9.24    9.34         9.34   48775500.0  0.08
27  Dec 07, 2020  9.31   9.33  9.15    9.22         9.22   58305200.0 -0.09
26  Dec 08, 2020  9.19   9.33  9.17    9.25         9.25   56296700.0  0.06
25  Dec 09, 2020  9.31   9.49  9.29    9.45         9.45   60780300.0  0.14
24  Dec 10, 2020  9.31   9.32  9.10    9.12         9.12   83372800.0 -0.19
23  Dec 11, 2020  9.19   9.19  9.01    9.02         9.02   73438200.0 -0.17
22  Dec 14, 2020  9.13   9.18  8.88    8.91         8.91   76826000.0 -0.22
21  Dec 15, 2020  9.03   9.15  8.94    9.15         9.15   69665900.0  0.12
20  Dec 16, 2020  9.17   9.18  8.97    9.04         9.04   55274500.0 -0.13
19  Dec 17, 2020  9.09   9.13  9.00    9.08         9.08   49301600.0 -0.01
18  Dec 18, 2020  9.09   9.09  8.91    8.95         8.95   78764600.0 -0.14
17  Dec 21, 2020  8.87   9.01  8.79    8.93         8.93   63908100.0  0.06
16  Dec 22, 2020  8.98   8.99  8.75    8.79         8.79   59031200.0 -0.19
15  Dec 23, 2020  8.82   9.03  8.80    8.99         8.99   54086700.0  0.17
14  Dec 24, 2020  9.01   9.02  8.80    8.86         8.86   27927000.0 -0.15
13  Dec 28, 2020  8.92   8.98  8.86    8.89         8.89   38068400.0 -0.03
12  Dec 29, 2020  8.93   8.93  8.78    8.82         8.82   37537900.0 -0.11
11  Dec 30, 2020  8.83   8.92  8.81    8.86         8.86   38461900.0  0.03
10  Dec 31, 2020  8.84   8.86  8.78    8.79         8.79   40135300.0 -0.05
9   Jan 04, 2021  8.81   8.84  8.43    8.52         8.52   85043100.0 -0.29
8   Jan 05, 2021  8.47   8.72  8.46    8.65         8.65   70127800.0  0.18
7   Jan 06, 2021  8.79   8.94  8.68    8.84         8.84   72590200.0  0.05
6   Jan 07, 2021  8.94   9.08  8.88    9.06         9.06   77117100.0  0.12
5   Jan 08, 2021  9.10   9.14  8.89    9.00         9.00   59121400.0 -0.10
4   Jan 11, 2021  8.87   9.32  8.82    9.30         9.30   96129500.0  0.43
3   Jan 12, 2021  9.30   9.82  9.29    9.78         9.78  124808500.0  0.48
2   Jan 13, 2021  9.91   9.92  9.64    9.78         9.78   89549300.0 -0.13
1   Jan 14, 2021  9.81  10.20  9.79   10.17        10.17  112695300.0  0.36
49  Nov 04, 2020  7.86   7.87  7.63    7.64         7.64   67326800.0 -0.22
48  Nov 05, 2020  7.76   7.99  7.71    7.99         7.99   61442600.0  0.23
47  Nov 06, 2020  8.01   8.02  7.75    7.79         7.79   50912100.0 -0.22
46  Nov 09, 2020  8.11   8.38  8.08    8.20         8.20  110511300.0  0.09
45  Nov 10, 2020  8.23   8.59  8.18    8.38         8.38   87468400.0  0.15
44  Nov 11, 2020  8.60   8.60  8.29    8.33         8.33   75644400.0 -0.27
43  Nov 12, 2020  8.26   8.29  8.10    8.21         8.21   81064900.0 -0.05
42  Nov 13, 2020  8.23   8.57  8.23    8.54         8.54   79475100.0  0.31
41  Nov 16, 2020  8.74   8.85  8.61    8.80         8.80   84853900.0  0.06
40  Nov 17, 2020  8.66   8.85  8.63    8.75         8.75   46754500.0  0.09
39  Nov 18, 2020  8.82   9.05  8.78    8.82         8.82   77759300.0  0.00
38  Nov 19, 2020  8.88   8.88  8.74    8.82         8.82   56672700.0 -0.06
37  Nov 20, 2020  8.81   8.82  8.68    8.74         8.74   57024300.0 -0.07
36  Nov 23, 2020  8.82   8.98  8.78    8.86         8.86   71537100.0  0.04
35  Nov 24, 2020  9.15   9.50  9.14    9.45         9.45   99520500.0  0.30
34  Nov 25, 2020  9.20   9.25  9.00    9.08         9.08   95217800.0 -0.12
33  Nov 27, 2020  9.12   9.14  9.03    9.09         9.09   27853900.0 -0.03